name: Hello World
#Triggers are configured under 
on: workflow_dispatch
jobs: 
  #provide name of the job
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Build Step
         run: echo "A Demo build"
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Test Phase
          run: echo "Running test cases"

    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Deploy the App
            run: echo "Deploying the app"
